---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Session information

### Session title

(_Some possibilities from Mark_)

__Opening up aquatic science__

__Aquatic science as open science__

***

### Attendees 

(_Enter your best estimate of the number of attendees, based on your knowledge of the topic and of individuals who would be interested._)

__100__


***

### Session format

(_Mark favors the standard format, but could be convinced otherwise._)

__X Standard 15-minute Talk Format__  
O Lightning Talks (Short presentations followed by discussion)  
O Panel Discussions  
O Posters  


***

### Description 

(_Describe the session in one paragraph; 500 words max._)

Science is about the discovery and sharing of information, but much of the process is often shrouded in mystery. The seemingly endless competition for limited research funding has led to notions that "knowledge is power" and "control is critical", which can hinder the exploration of new ideas or methodologies. Furthermore, we are also witnessing an increase in journal retractions and scientists’ inability to successfully reproduce previous findings. Fortunately, however, there is a growing movement among scientists to embrace newer technological developments that allow for more transparent design, execution, analysis, and dissemination of research. 

This session will highlight a variety of examples of tools and best practices in the open science process, including data management, reproducible workflows, and options for collaboration and dissemination of results.


***

### List up to five keywords

(_A few suggestions from Mark_)

* open science
* reproducible research
* data stewardship
* synthesis


***

### List of potential speakers and topics

| Last Name | First Name | Email | Presentation Topic | Tentative Title | Speaker invited? | Speaker tentatively confirmed? |
|-----------|------------|-------|--------------------|-----------------|:----------------:|:------------------------------:|
| De Cicco | Laura | ldecicco@usgs.gov | Discovering and retrieving water data available from Federal hydrologic web services | [tentative title] | N | N |
| Hollister | Jeff | hollister.jeff@epa.gov | Calculating lake morphometry metrics  | [tentative title] | N | N |
| Holmes | Elizabeth | eli.holmes@noaa.gov | Using multivariate autoregressive models to estimate extinction risks | [tentative title] | N | N |
| Pedersen | Eric | eric.pedersen@concordia.ca | Dynamics of abrupt change and regime shifts in metacommunities | [tentative title] | N | N |
| Simpson | Gavin | gavin.simpson@uregina.ca | Modelling palaeoecological time series using generalized additive models | [tentative title] | N | N |

